### ISSUE TITLE
Kestra internal storage URI in "from" attribute gives error on amqp.Publish

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/plugin-amqp#36]
### Expected Behavior

The items in the file should have got published to RabbitMQ.

### Actual Behaviour

In publish_to_amqp task, getting an error:
```
Invalid from parameter, must be a Kestra internal storage uri
```

### Steps To Reproduce

Run this flow with appropriate amqp host and exchange:

```yaml
id: orders_to_amqp
namespace: blueprint

tasks:
  - id: csv
    type: io.kestra.plugin.fs.http.Download
    uri: https://raw.githubusercontent.com/kestra-io/datasets/main/csv/orders.csv

  - id: csv_to_ion
    type: io.kestra.plugin.serdes.csv.CsvReader
    from: "{{ outputs.csv.uri }}"
  - id: publish_to_amqp
    type: "io.kestra.plugin.amqp.Publish"
    url: amqp://guest:guest@localhost:5672/
    exchange: input-queue
    from: "{{ outputs.csv_to_ion.uri }}"
```

### Environment Information

- Kestra Version: 0.13.8
- Plugin version: latest
- Operating System (OS / Docker / Kubernetes): Docker
- Java Version (If not docker): N/A
